// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemChecker.API.Data;

#nullable disable

namespace SystemChecker.API.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemChecker.API.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("SystemChecker.API.Models.CpuStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.Property<double>("UsagePercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId")
                        .IsUnique();

                    b.ToTable("CpuStatus");
                });

            modelBuilder.Entity("SystemChecker.API.Models.DiskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("FreeSpace")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.Property<long>("TotalSpace")
                        .HasColumnType("bigint");

                    b.Property<double>("UsagePercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId");

                    b.ToTable("DiskStatus");
                });

            modelBuilder.Entity("SystemChecker.API.Models.FolderChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId");

                    b.ToTable("FolderChanges");
                });

            modelBuilder.Entity("SystemChecker.API.Models.FolderMonitorConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CheckZeroByteFiles")
                        .HasColumnType("bit");

                    b.Property<int>("MachineConfigurationId")
                        .HasColumnType("int");

                    b.Property<bool>("MonitorLastModified")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShouldBeEmpty")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MachineConfigurationId");

                    b.ToTable("FolderMonitorConfigs");
                });

            modelBuilder.Entity("SystemChecker.API.Models.FolderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Exists")
                        .HasColumnType("bit");

                    b.Property<bool>("HasZeroByteFiles")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("ZeroByteFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId");

                    b.ToTable("FolderStatuses");
                });

            modelBuilder.Entity("SystemChecker.API.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("SystemChecker.API.Models.MachineConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddressesToMonitor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("ServicesToMonitor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcpPorts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.ToTable("MachineConfigurations");
                });

            modelBuilder.Entity("SystemChecker.API.Models.MemoryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AvailablePhysicalMemory")
                        .HasColumnType("bigint");

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.Property<long>("TotalPhysicalMemory")
                        .HasColumnType("bigint");

                    b.Property<double>("UsagePercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId")
                        .IsUnique();

                    b.ToTable("MemoryStatus");
                });

            modelBuilder.Entity("SystemChecker.API.Models.MonitoredAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReachable")
                        .HasColumnType("bit");

                    b.Property<int>("NetworkStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTime")
                        .HasColumnType("int");

                    b.Property<int?>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NetworkStatusId");

                    b.HasIndex("SystemCheckHistoryId");

                    b.ToTable("MonitoredAddresses");
                });

            modelBuilder.Entity("SystemChecker.API.Models.NetworkStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveInterfaces")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasInternetAccess")
                        .HasColumnType("bit");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId")
                        .IsUnique();

                    b.ToTable("NetworkStatuses");
                });

            modelBuilder.Entity("SystemChecker.API.Models.ServiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId");

                    b.ToTable("ServiceStatus");
                });

            modelBuilder.Entity("SystemChecker.API.Models.SystemCheckHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.TcpPortStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Service")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemCheckHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemCheckHistoryId");

                    b.ToTable("TcpPortStatus");
                });

            modelBuilder.Entity("SystemChecker.API.Models.ApiKey", b =>
                {
                    b.HasOne("SystemChecker.API.Models.Machine", "Machine")
                        .WithOne("ApiKey")
                        .HasForeignKey("SystemChecker.API.Models.ApiKey", "MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SystemChecker.API.Models.CpuStatus", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithOne("Cpu")
                        .HasForeignKey("SystemChecker.API.Models.CpuStatus", "SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.DiskStatus", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithMany("Disks")
                        .HasForeignKey("SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.FolderChange", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithMany("FolderChanges")
                        .HasForeignKey("SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.FolderMonitorConfig", b =>
                {
                    b.HasOne("SystemChecker.API.Models.MachineConfiguration", "MachineConfiguration")
                        .WithMany("MonitoredFolders")
                        .HasForeignKey("MachineConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineConfiguration");
                });

            modelBuilder.Entity("SystemChecker.API.Models.FolderStatus", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithMany("Folders")
                        .HasForeignKey("SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.MachineConfiguration", b =>
                {
                    b.HasOne("SystemChecker.API.Models.Machine", "Machine")
                        .WithOne()
                        .HasForeignKey("SystemChecker.API.Models.MachineConfiguration", "MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SystemChecker.API.Models.MemoryStatus", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithOne("Memory")
                        .HasForeignKey("SystemChecker.API.Models.MemoryStatus", "SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.MonitoredAddress", b =>
                {
                    b.HasOne("SystemChecker.API.Models.NetworkStatus", "NetworkStatus")
                        .WithMany("MonitoredAddresses")
                        .HasForeignKey("NetworkStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", null)
                        .WithMany("MonitoredAddresses")
                        .HasForeignKey("SystemCheckHistoryId");

                    b.Navigation("NetworkStatus");
                });

            modelBuilder.Entity("SystemChecker.API.Models.NetworkStatus", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithOne("Network")
                        .HasForeignKey("SystemChecker.API.Models.NetworkStatus", "SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.ServiceStatus", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithMany("Services")
                        .HasForeignKey("SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.SystemCheckHistory", b =>
                {
                    b.HasOne("SystemChecker.API.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SystemChecker.API.Models.TcpPortStatus", b =>
                {
                    b.HasOne("SystemChecker.API.Models.SystemCheckHistory", "SystemCheckHistory")
                        .WithMany("Ports")
                        .HasForeignKey("SystemCheckHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCheckHistory");
                });

            modelBuilder.Entity("SystemChecker.API.Models.Machine", b =>
                {
                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("SystemChecker.API.Models.MachineConfiguration", b =>
                {
                    b.Navigation("MonitoredFolders");
                });

            modelBuilder.Entity("SystemChecker.API.Models.NetworkStatus", b =>
                {
                    b.Navigation("MonitoredAddresses");
                });

            modelBuilder.Entity("SystemChecker.API.Models.SystemCheckHistory", b =>
                {
                    b.Navigation("Cpu");

                    b.Navigation("Disks");

                    b.Navigation("FolderChanges");

                    b.Navigation("Folders");

                    b.Navigation("Memory");

                    b.Navigation("MonitoredAddresses");

                    b.Navigation("Network");

                    b.Navigation("Ports");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
